on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

name: Purge gypsum projects

jobs:
  purge-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache modules
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: node-${{ hashFiles('**/package.json') }}

      - name: Set up Node
        uses: actions/setup-node@v3.4.1

      - name: Install required packages
        run: npm i

      - name: Purge projects
        run: |
          source config.sh
          node src/purge-projects.js \
            --r2bucket gypsum-test \
            --ghrepo ${{ github.repository }} \
            --cfid $CF_ACCOUNT_ID \
            --r2key ${{ secrets.R2_ACCESS_KEY_ID }} \
            --r2secret ${{ secrets.R2_SECRET_ACCESS_KEY }} \
            --ghtoken ${{ secrets.GH_BOT_TOKEN }}
